- id: ts-no-console-log
  name: check for console.()
  description: 'Prevent console.log'
  entry: '\bconsole.(log|info)\('
  language: pygrep
  types: [ts]

- id: ts-no-focus-test
  name: check for xit/fdescribe/...
  description: 'Prevent excluded / focused tests'
  entry: '\b[fx](describe|it)\('
  language: pygrep
  files: \.spec\.(ts|js)$

- id: ts-accessing-window
  name: check for accessing window
  description: 'Prevent writing to the window object'
  entry: '\(?window( as any)?\)?\.(.)+\s=\s(.)+'
  language: pygrep
  types: [ts]

- id: ts-debugger
  name: check for debugger calls
  description: 'Prevent calls to debugger'
  entry: '\bdebugger'
  language: pygrep
  types: [ts]